apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        # annotations:
        #   io.cilium/lb-ipam-ips: ${ENVOY_GATEWAY_LOAD_BALANCER_IP}
  shutdown:
    drainTimeout: 180s
  
  # Open Telemetry
  telemetry:
    accessLog:
      settings:
        - sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - name: otel-collector
                    namespace: monitoring
                    port: 4317
                resourceAttributes:
                  service.name: envoy-gateway-proxy
                  service.namespace: envoy-gateway-system
                  telemetry.source: envoy-accesslog
          format:
            type: Text
            text: |
              [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
    tracing:
      samplingRate: 100
      provider:
        type: OpenTelemetry
        serviceName: envoy-gateway-proxy
        backendRefs:
          - name: otel-collector
            namespace: monitoring
            port: 4317
    metrics:
      prometheus:
        compression:
          type: Gzip
      providers:
        - type: OpenTelemetry
          openTelemetry:
            backendRefs:
              - name: otel-collector
                namespace: monitoring
                port: 4317
            resourceAttributes:
              service.name: envoy-gateway-proxy
              service.namespace: envoy-gateway-system