apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# product-service Kustomize base
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: product-service
      app.kubernetes.io/part-of: e-commerce
