# ExternalSecrets — reviews-service (e-commerce namespace)
# Provisions: reviews-service-mongodb-secret, reviews-service-oauth-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reviews-service-mongodb-secret
  namespace: e-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: reviews-service-mongodb-secret
    creationPolicy: Owner
    template:
      data:
        MONGODB_URI: "mongodb://reviews_owner:{{ .password }}@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017/reviews?authSource=admin&replicaSet=mongodb"
  data:
    - secretKey: password
      remoteRef:
        key: /mongodb/reviews
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reviews-service-oauth-secret
  namespace: e-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: reviews-service-oauth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /ecommerce/reviews-service-oauth
