apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Kafka — Strimzi Kafka cluster + KafkaTopic + KafkaUser CRs
# Namespace: kafka
resources:
  - cluster.yaml
  - topics.yaml
  - users.yaml
