# order-service Kustomize base
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: order-service
      app.kubernetes.io/part-of: e-commerce
