# notification-service Kustomize base
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: notification-service
  app.kubernetes.io/part-of: e-commerce
