apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-routing-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-routing-app
  interval: 10m
  path: ./gitops/infrastructure/environments/staging/routing/config
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
